<a href="https://colab.research.google.com/github/a-forty-two/EY_batch_7_09-Sept/blob/main/Intro_to_words_and_vectors_part2_withvectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import imdb

In [3]:
dir(imdb)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'get_word_index',
 'load_data']

In [4]:
wordindex = imdb.get_word_index()
data = imdb.load_data()

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [6]:
len(data)

2

In [7]:
len(data[0])

2

In [8]:
len(data[1])

2

In [13]:
print(data[0][0][0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [14]:
print(data[0][1][0])

1


In [15]:
print(data[0][1])

[1 0 0 ... 0 1 0]


In [17]:
# all unique values inside our output

# data structures, lambdas, list comprehensions
set(data[0][1])
# MOST LIKELY-> sentiment

{0, 1}

In [85]:
#data # -> 4 elements ->

In [84]:
#wordindex

In [19]:
revwordindex = {}

for word,idx in wordindex.items():
  revwordindex[idx] = word

print(revwordindex)

{34701: 'fawn', 52006: 'tsukino', 52007: 'nunnery', 16816: 'sonja', 63951: 'vani', 1408: 'woods', 16115: 'spiders', 2345: 'hanging', 2289: 'woody', 52008: 'trawling', 52009: "hold's", 11307: 'comically', 40830: 'localized', 30568: 'disobeying', 52010: "'royale", 40831: "harpo's", 52011: 'canet', 19313: 'aileen', 52012: 'acurately', 52013: "diplomat's", 25242: 'rickman', 6746: 'arranged', 52014: 'rumbustious', 52015: 'familiarness', 52016: "spider'", 68804: 'hahahah', 52017: "wood'", 40833: 'transvestism', 34702: "hangin'", 2338: 'bringing', 40834: 'seamier', 34703: 'wooded', 52018: 'bravora', 16817: 'grueling', 1636: 'wooden', 16818: 'wednesday', 52019: "'prix", 34704: 'altagracia', 52020: 'circuitry', 11585: 'crotch', 57766: 'busybody', 52021: "tart'n'tangy", 14129: 'burgade', 52023: 'thrace', 11038: "tom's", 52025: 'snuggles', 29114: 'francesco', 52027: 'complainers', 52125: 'templarios', 40835: '272', 52028: '273', 52130: 'zaniacs', 34706: '275', 27631: 'consenting', 40836: 'snuggle

In [21]:
print(data[0][0][42]) # individual movie review

[1, 1710, 14, 733, 1367, 1028, 81, 24, 332, 48, 25, 92, 181, 49, 757, 2029, 8, 25, 159, 25, 106, 4, 22, 10, 10, 19, 6, 177, 40, 14, 25, 594, 726, 42, 24, 4, 156, 5, 1507, 697, 618, 51, 36, 71, 397, 83, 122, 36, 67, 4, 229, 5, 135, 1400, 491, 3267, 7, 4, 840, 243, 16, 141, 6, 569, 15, 14, 31, 191, 1854, 758, 472, 12, 127, 122, 36, 60, 104, 8, 808, 23, 4, 2030, 12830, 13, 384, 62, 25, 81, 6, 20, 19, 4, 167, 7, 6, 20, 446, 12785, 21546, 758, 22198, 2595, 37, 62, 303, 140, 23, 8, 1504, 4, 3149, 477, 1351, 758, 93, 14, 12, 166, 25, 594, 89, 4, 84, 7, 736, 1067, 750, 5083, 100, 4225, 477, 42894, 5, 340, 717, 46, 23, 4, 994, 758, 10, 10, 4, 22, 9, 270, 11, 6, 392, 513, 11, 162, 2713, 6, 117, 430, 5, 250, 26, 11, 4, 890, 38451, 31, 314, 54, 6, 976, 14959, 17195, 6640, 6, 8047, 739, 5, 32557, 120, 98, 11, 242, 4, 249, 318, 962, 720, 7, 4, 22, 4, 1693, 19508, 49, 243, 7, 767, 14789, 23, 98, 12, 610, 40, 2595, 69, 1428, 6, 30471, 7, 1093, 11, 39, 7, 4, 370, 7315, 5, 23744, 27, 25987, 7389, 11, 12

In [24]:
def decoder(input):
  decoded_sentence = []
  for inp in input:
    decoded_sentence.append(revwordindex[inp])
  return decoded_sentence



In [26]:
print(decoder(data[0][0][42]))

['the', 'rarely', 'as', 'mystery', 'places', 'social', 'people', 'his', "you're", 'what', 'have', 'then', 'pretty', 'good', 'mention', 'remembered', 'in', 'have', 'new', 'have', 'character', 'of', 'you', 'i', 'i', 'film', 'is', 'down', 'just', 'as', 'have', 'brother', 'similar', "it's", 'his', 'of', 'before', 'to', 'system', 'comic', 'musical', 'when', 'from', 'than', 'often', 'first', 'off', 'from', 'can', 'of', 'guy', 'to', 'why', 'minor', 'wants', 'eerie', 'br', 'of', 'particular', 'yet', 'with', 'should', 'is', 'particularly', 'for', 'as', 'by', 'big', 'knowledge', 'lady', '\x96', 'that', 'end', 'off', 'from', 'which', 'two', 'in', 'season', 'are', 'of', 'deals', 'yakuza', 'was', 'let', 'story', 'have', 'people', 'is', 'on', 'film', 'of', 'going', 'br', 'is', 'on', 'oh', 'forbid', 'chintzy', 'lady', 'goodie', 'regret', 'like', 'story', 'seem', 'through', 'are', 'in', 'actresses', 'of', 'millions', 'amazing', 'batman', 'lady', 'way', 'as', 'that', 'find', 'have', 'brother', "don't",

In [28]:
" ".join(decoder(data[0][0][42]))

"the rarely as mystery places social people his you're what have then pretty good mention remembered in have new have character of you i i film is down just as have brother similar it's his of before to system comic musical when from than often first off from can of guy to why minor wants eerie br of particular yet with should is particularly for as by big knowledge lady \x96 that end off from which two in season are of deals yakuza was let story have people is on film of going br is on oh forbid chintzy lady goodie regret like story seem through are in actresses of millions amazing batman lady way as that find have brother don't of great br appears hold dull connery after tie amazing socioeconomic to used sequence some are of fighting lady i i of you it place this is playing kill this actually spite is over worse to fun he this of hot klum by left no is telling stirba catering establish is joint george to wise's show any this away of sure excellent personal paul br of you of mid dwind

In [29]:
" ".join(decoder(data[0][0][5420]))

"the as on with worst funny hope br my such mother such people was perfect league film's just as play wonder stupid we laced mother much those in of on they act pie image it away main that what have had had town of how on just was off to out pretty in season some sorry she this of performance com on diplomat american out in perfect good death before to insults strongest them br screen as it of on but have not what have he set but is very on film very love to is working little based meyer them as on it itself but have kills career watching curse they where as on floor career was one in appear for soundtrack follow in that with relationship much dewames to was mediocre world is again gets user's they of enjoy seems not asian was with graham not an this an of again seems for questions find of career unlikely interesting that's in could as on main that they an superb have lose cruz act br mike by br of try theater characters your"

In [32]:
print(data[0][0][5420])

[1, 14, 20, 16, 246, 160, 437, 7, 58, 138, 449, 138, 81, 13, 401, 2753, 595, 40, 14, 294, 591, 376, 72, 8647, 449, 73, 145, 8, 4, 20, 33, 508, 3271, 1456, 9, 242, 290, 12, 48, 25, 66, 66, 510, 4, 86, 20, 40, 13, 122, 5, 43, 181, 8, 808, 46, 803, 56, 11, 4, 236, 2363, 20, 18033, 295, 43, 8, 401, 49, 338, 156, 5, 6243, 5652, 95, 7, 265, 14, 9, 4, 20, 18, 25, 21, 48, 25, 26, 267, 18, 6, 52, 20, 19, 52, 116, 5, 6, 777, 114, 445, 7841, 95, 14, 20, 9, 407, 18, 25, 1095, 608, 146, 3173, 33, 118, 14, 20, 1870, 608, 13, 28, 8, 974, 15, 813, 791, 8, 12, 16, 646, 73, 87165, 5, 13, 1498, 179, 6, 171, 211, 28704, 33, 4, 355, 183, 21, 2185, 13, 16, 5184, 21, 32, 11, 32, 4, 171, 183, 15, 1201, 166, 4, 608, 2385, 218, 195, 8, 97, 14, 20, 290, 12, 33, 32, 894, 25, 1582, 10794, 508, 7, 1949, 31, 7, 4, 350, 747, 102, 126]


In [33]:
for i in range(20):
  print(data[0][0][i])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
[1, 194, 1153, 194, 8255, 78, 228, 5

In [ ]:
# Certain generally used flags in NLP->

# <PAD> 0
# <START> 1
# <UNKNOWN> 2
# <UNUSED> 3


# anything X 0 = ? = 0

# w1 X 0 = 0 = no learning

# 10 word sentence, but my NN expects 20 words
# solution -> add 10 <PAD> into this sentence making it 20 words long

# w11...w20 X 0 = 0

In [38]:
revwordindex[3]

'a'

In [37]:
revwordindex[2]

'and'

In [36]:
revwordindex[1]

'the'

In [39]:
# ERROR IS EXPECTED; move on to the next cell
revwordindex[0]

KeyError: 0

In [41]:
# fix the dictionary

# need space in the beginning of dictionary

# 0th doesnt exist in our wordindex, but 1,2,3 do!

# begin by shifting all the words by 3 positions!!!

new_dictionary = {}
for word,index in wordindex.items():
  new_dictionary[word] = index + 3

# space has been made to insert the NLP flags of pad, start, unknown and unused

new_dictionary["<PAD>"] = 0
new_dictionary["<START>"] = 1
new_dictionary["<UNK>"] = 2
new_dictionary["<UNUSED>"] = 3

In [42]:
rev_new_dict = {}
for word,index in new_dictionary.items():
  rev_new_dict[index] = word

In [43]:
print(rev_new_dict)

{34704: 'fawn', 52009: 'tsukino', 52010: 'nunnery', 16819: 'sonja', 63954: 'vani', 1411: 'woods', 16118: 'spiders', 2348: 'hanging', 2292: 'woody', 52011: 'trawling', 52012: "hold's", 11310: 'comically', 40833: 'localized', 30571: 'disobeying', 52013: "'royale", 40834: "harpo's", 52014: 'canet', 19316: 'aileen', 52015: 'acurately', 52016: "diplomat's", 25245: 'rickman', 6749: 'arranged', 52017: 'rumbustious', 52018: 'familiarness', 52019: "spider'", 68807: 'hahahah', 52020: "wood'", 40836: 'transvestism', 34705: "hangin'", 2341: 'bringing', 40837: 'seamier', 34706: 'wooded', 52021: 'bravora', 16820: 'grueling', 1639: 'wooden', 16821: 'wednesday', 52022: "'prix", 34707: 'altagracia', 52023: 'circuitry', 11588: 'crotch', 57769: 'busybody', 52024: "tart'n'tangy", 14132: 'burgade', 52026: 'thrace', 11041: "tom's", 52028: 'snuggles', 29117: 'francesco', 52030: 'complainers', 52128: 'templarios', 40838: '272', 52031: '273', 52133: 'zaniacs', 34709: '275', 27634: 'consenting', 40839: 'snuggle

In [44]:
def new_decoder(input):
  decoded_sentence = []
  for inp in input:
    decoded_sentence.append(rev_new_dict[inp])
  return decoded_sentence

In [48]:
" ".join(new_decoder(data[0][0][2]))

"<START> this has to be one of the worst films of the 1990s when my friends i were watching this film being the target audience it was aimed at we just sat watched the first half an hour with our jaws touching the floor at how bad it really was the rest of the time everyone else in the theatre just started talking to each other leaving or generally crying into their popcorn that they actually paid money they had earnt working to watch this feeble excuse for a film it must have looked like a great idea on paper but on film it looks like no one in the film has a clue what is going on crap acting crap costumes i can't get across how embarrasing this is to watch save yourself an hour a bit of your life"

In [49]:
data[0][1][2] # corresponding output to above input

0

In [55]:
" ".join(new_decoder(data[0][0][116]))

"<START> as a another reviewer states hanna's war is an outstanding film about an outstanding person hanna anniko senesh who would become the jewish joan of arc unfortunately i diverge in opinion not agreeing that miss detmers as the lead is too beautiful to be taken seriously as a resistance fighter in truth for me her performance is not held back by her beauty but makes it all the more stark in the terror of the sadistic brutality as a resistor she faces maruschka detmers performance is brave poignant heartfelt or understood and totally believable in other words for me in the zone from the opening credits if you would like to learn about the suffering of someone else for something they believe in and be impressively entertained give hanna's war with maruschka detmers a try my hat is off also to ellen burstyn as hanna's mother a much well known and famous actress who could have made effort to walk off with the film in that it is a team effort perhaps of two actress' but not an all abo

In [54]:
data[0][1][116]# corresponding output to above input

1

In [57]:
for i in range(100,105):
  print()
  print(" ".join(new_decoder(data[0][0][i])))


<START> i am a great fan of david lynch and have everything that he's made on dvd except for hotel room the 2 hour twin peaks movie so when i found out about this i immediately grabbed it and and what is this it's a bunch of crudely drawn black and white cartoons that are loud and foul mouthed and unfunny maybe i don't know what's good but maybe this is just a bunch of crap that was foisted on the public under the name of david lynch to make a few bucks too let me make it clear that i didn't care about the foul language part but had to keep adjusting the sound because my neighbors might have all in all this is a highly disappointing release and may well have just been left in the deluxe box set as a curiosity i highly recommend you don't spend your money on this 2 out of 10

<START> whoever wrote up redline as a great car movie must be getting paid off by daniel sadek to promote this ultra crappy flaming steaming pile of amateur crap easily the worst automotive movie or any movie ever

In [60]:
len(rev_new_dict)

88588

In [64]:
HP_WORDS_ALLOWED = 10000

In [65]:
#just for demo, let's consider a subset of these 88,588 words!
# maybe top-10K!

# <UNK>
(xtrain,ytrain),(xtest, ytest) = imdb.load_data(num_words=HP_WORDS_ALLOWED)

In [62]:
# ytrain, ytest should contain 1s and 0
ytrain[:2], ytest[:2]

(array([1, 0]), array([0, 1]))

In [63]:
for i in range(100,105):
  print()
  print(" ".join(new_decoder(xtrain[i])))


<START> i am a great fan of david lynch and have everything that he's made on dvd except for hotel room the 2 hour twin peaks movie so when i found out about this i immediately grabbed it and and what is this it's a bunch of <UNK> drawn black and white cartoons that are loud and foul mouthed and unfunny maybe i don't know what's good but maybe this is just a bunch of crap that was <UNK> on the public under the name of david lynch to make a few bucks too let me make it clear that i didn't care about the foul language part but had to keep <UNK> the sound because my neighbors might have all in all this is a highly disappointing release and may well have just been left in the <UNK> box set as a curiosity i highly recommend you don't spend your money on this 2 out of 10

<START> whoever wrote up <UNK> as a great car movie must be getting paid off by daniel <UNK> to promote this ultra crappy <UNK> steaming pile of amateur crap easily the worst <UNK> movie or any movie ever made this makes <

In [71]:
model = keras.Sequential([
    keras.layers.Embedding(input_dim=HP_WORDS_ALLOWED,output_dim=32 )
])

In [72]:
model.summary() # empty embedding layer

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [81]:
# prompt: pass a sentence to my model with embedding layer only and show the output vectors

# Example sentence
sentence = xtrain[0]

# Convert the sentence to a tensor
sentence_tensor = tf.convert_to_tensor(sentence)

# Add a batch dimension
sentence_tensor = tf.expand_dims(sentence_tensor, axis=0)

# Pass the sentence to the model
output = model(sentence_tensor)

# Print the output vectors
print(output)


tf.Tensor(
[[[-0.03236075  0.0032949  -0.03617505 ...  0.00949906  0.00581817
    0.04699272]
  [ 0.00740571 -0.0249434  -0.01033962 ... -0.02114538 -0.00270003
   -0.04420135]
  [ 0.00205804  0.02802309 -0.00349374 ... -0.01066893  0.01715763
    0.00830841]
  ...
  [ 0.02608578  0.02117177 -0.02096385 ...  0.00120894  0.0447773
   -0.0263509 ]
  [ 0.03750235 -0.00634967 -0.03548877 ...  0.02712296  0.00894554
    0.00672175]
  [-0.03381222 -0.01021577  0.0401275  ...  0.00229181 -0.02823933
   -0.04196459]]], shape=(1, 218, 32), dtype=float32)


In [83]:
output[0][0]

<tf.Tensor: shape=(32,), dtype=float32, numpy=
array([-0.03236075,  0.0032949 , -0.03617505,  0.00827175, -0.03210672,
       -0.01645492, -0.04465164,  0.00973652, -0.02289036,  0.02122455,
        0.02352059,  0.03737036,  0.0490079 , -0.00013389, -0.04718326,
        0.02356753,  0.0131724 , -0.02751446,  0.02822113, -0.00210165,
       -0.03617992,  0.02057988,  0.00604262,  0.0113806 , -0.03193444,
       -0.04678036, -0.01713793,  0.0242591 ,  0.01825359,  0.00949906,
        0.00581817,  0.04699272], dtype=float32)>